"""Named appearance palettes for Dani and the preserved Jarvis interface."""

THEMES = {
    "dani": {
        "label": "Dani — clear and calm",
        "bg": "#f5f7fb",
        "bg_raised": "#ffffff",
        "accent": "#245a9b",
        "accent_hi": "#173e70",
        "text": "#1f2937",
        "muted": "#4b5563",
        "amber": "#815000",
        "red": "#a61b1b",
        "idle": "#596579",
        "panel_fill": "#ffffff",
        "panel_edge": "#d6deea",
        "font": "Segoe UI",
        "font_semibold": "Segoe UI Semibold",
        "font_light": "Segoe UI",
        "button_font": "Segoe UI Semibold",
    },
    "jarvis": {
        "label": "Jarvis Classic — original HUD",
        "bg": "#060b12",
        "bg_raised": "#0a1520",
        "accent": "#38d6ff",
        "accent_hi": "#b4f4ff",
        "text": "#d8f4ff",
        "muted": "#7fa6b8",
        "amber": "#ffb02e",
        "red": "#ff5468",
        "idle": "#6d8190",
        "panel_fill": "#09141f",
        "panel_edge": "#24424f",
        "font": "Bahnschrift",
        "font_semibold": "Bahnschrift SemiBold",
        "font_light": "Bahnschrift SemiLight",
        "button_font": "Bahnschrift SemiBold SemiCondensed",
    },
}
